services:
  app:
    image: 'marchocode/clash-merger:latest'
    container_name: mihomo
    restart: unless-stopped
    # 8080
    network_mode: host
    environment:
    # system scope token is optional
      TOKEN: B13CFDA6-947E-4AAD-BEE8-6A475313C80F
    volumes:
      - "./config.yaml:/config.yaml"